[mypy]
python_version = 3.11
strict_optional = True
warn_unused_ignores = True
ignore_missing_imports = True
follow_imports = silent
disable_error_code = import-untyped

[mypy-tests.*]
ignore_errors = True

[mypy-alembic.*]
ignore_errors = True
