apiVersion: v1
kind: Service
metadata:
  name: {{ include "pegase.fullname" . }}-api
  labels:
    {{- include "pegase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "pegase.selectorLabels" . | nindent 4 }}
    component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      name: http
