apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pegase.fullname" . }}-worker
  labels:
    {{- include "pegase.labels" . | nindent 4 }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "pegase.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "pegase.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - pegase.tasks.celery_app
            - worker
            - --loglevel=INFO
            - --concurrency={{ .Values.worker.concurrency }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: audit
              mountPath: /var/lib/pegase
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: audit
          {{- if .Values.persistence.audit.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pegase.fullname" . }}-audit
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
